# Generated by Django 4.1.5 on 2023-06-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('p_code', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('face_encodings', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'User Register',
            },
        ),
    ]
