# Generated by Django 4.1.5 on 2023-06-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_register_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=250)),
                ('manager_name', models.CharField(blank=True, max_length=250)),
                ('company_location', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Company Register',
            },
        ),
    ]
